### ISSUE TITLE
App Flickers Upon Each Data Fetch

### ISSUE THREAD

**Issue by manavm1990** [cassidoo/book-rating-demo#1]
Although it's 🆒  to use `refresh`, it appears that the entire table re-renders causing a 'flicker' effect. How might we take advantage of the 'auto-refresh' and only add the additional values without 'flickering' the whole page each time @cassidoo ?

**Comment by cassidoo** [comment]
The best way to do this would probably be some kind of cache. What I would probably do is save the values into localStorage, and then populate the table with that, and then if the database values change, *then* refresh the table (+localStorage). Because it was a live demo, I didn't get a chance to do smarter things like that.

Also, to clarify, luckily the entire page isn't flickering (thanks, React). It is just the table, but because the table is the only thing on the page, it currently appears to be the whole page.

**Comment by manavm1990** [comment]
[I didn't end up using any `Storage` - just `useEffect` and `useState`](https://github.com/manavm1990/harperdb-demo/commit/099638cb6d902360e86dec566b0d0c398ce15096) - should I have?
Tx for your time.

**Comment by cassidoo** [comment]
Oh yes, definitely! I didn't really clarify, using localStorage would be in addition to useState and useEffect. Saving to local means that you would get a faster load time, too, if you were joining the site after navigating away.
